# -*- coding: utf-8 -*-
"""exp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqqoW9YLiFUnbp5i3lb0D70sT1x7I8aq
"""

def caesar_encrypt(text, shift):
    """Encrypts a given text using the Caesar cipher."""
    result = ""
    for char in text:
        if char.isalpha():  # Check if the character is an alphabet letter
            start = ord('a') if char.islower() else ord('A')
            shifted_char = chr((ord(char) - start + shift) % 26 + start)
            result += shifted_char
        else:
            result += char  # Keep non-alphabetic characters as they are
    return result

def caesar_decrypt(text, shift):
    """Decrypts a given text using the Caesar cipher."""
    # Decryption is simply encryption with a negative shift
    return caesar_encrypt(text, -shift)

# Demonstration of Caesar Cipher

message = "Hello, World! This is a secret message."
shift_key = 3 # The 'key' for our cipher

print(f"Original Message: {message}")
print(f"Shift Key: {shift_key}")

# Encrypt the message
encrypted_message = caesar_encrypt(message, shift_key)
print(f"Encrypted Message: {encrypted_message}")

# Decrypt the message
decrypted_message = caesar_decrypt(encrypted_message, shift_key)
print(f"Decrypted Message: {decrypted_message}")

# Demonstrate confidentiality: if the key is unknown, the message remains confidential
print("\n--- Demonstrating Confidentiality ---")
wrong_shift_key = 5
print(f"Trying to decrypt with wrong key ({wrong_shift_key}): {caesar_decrypt(encrypted_message, wrong_shift_key)}")